# -*- mode: python ; coding: utf-8 -*-

# Lista completa de módulos hidden necesarios para pybricksdev
hiddenimports = [
    'pybricksdev',
    'pybricksdev.ble',
    'pybricksdev.connections',
    'pybricksdev.connections.pybricks',
    'pybricksdev.ble.lwp3',
    'pybricksdev.ble.nus',
    'pybricksdev.ble.pybricks',
    'bleak',
    'bleak.backends',
    'bleak.backends.winrt',
    'bleak.backends.winrt.client',
    'bleak.backends.winrt.scanner',
    'bleak.backends.winrt.characteristic',
    'bleak.backends.winrt.service',
    'bleak.backends.winrt.descriptor',
    'bleak.backends.winrt.util',
    'winrt',
    'winrt.windows.devices.bluetooth',
    'winrt.windows.devices.bluetooth.advertisement',
    'winrt.windows.devices.bluetooth.genericattributeprofile',
    'winrt.windows.devices.enumeration',
    'winrt.windows.devices.radios',
    'winrt.windows.foundation',
    'winrt.windows.foundation.collections',
    'winrt.windows.storage.streams',
    'asyncio',
    'pygame',
    'tkinter',
    'tempfile',
    'queue',
    'threading',
]

a = Analysis(
    ['SistemaControlSpike.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SistemaControlSpike',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
